### ISSUE TITLE
请问cfenet800-vgg对于coco数据集测得的AP是多少呢？

### ISSUE THREAD

**Issue by happog** [qijiezhao/CFENet#14]
如题，多谢

**Comment by qijiezhao** [comment]
We didn't have a stable result of CFENet800, because:
1, Training CFENet800 is better to implement on P40 or V100, you should ensure the batch size per GPU.
2, The training time is very time-consuming, we only have trained it on small-scale datasets, e.g., the competitions. For, MS-COCO, usually cost more than 2 or 3 weeks, we don't have too much resource.
However, you can deduce the result by referring to the result of M2Det800-vgg.

**Comment by happog** [comment]
好的，非常感谢！
